#ifndef CONSTANTS_H
#define CONSTANTS_H

#define THREADS_PER_LOCAL_SORT 128
#define THREADS_PER_GLOBAL_SORT 128

#define BIT_COUNT_PARALLEL 4
#define RADIX_PARALLEL (1 << BIT_COUNT_PARALLEL)

#define BIT_COUNT_SEQUENTIAL 8
#define RADIX_SEQUENTIAL (1 << BIT_COUNT_SEQUENTIAL)
#define RADIX_MASK_SEQUENTIAL ((1 << BIT_COUNT_SEQUENTIAL) - 1)

#endif
